spring:
  application:
    name: MyPersonalBudget
  main:
    banner-mode: console
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:budget_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:budget_user}
    password: ${MYSQL_PASSWORD:budget_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      schema-locations: classpath:db/ddl/db_schema_mysql.sql
      data-locations: classpath:db/dml/db_data.sql
      mode: always 